[env]
TERM = "xterm-256color"

[shell]
program = "bash"

[window]
padding.x = 16
padding.y = 14
opacity = 0.97
resize_increments = true

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
